{% set name = "vcf_snps_utils" %}
{% set version = "v0.0.3-beta" %}
{% set sha256 = "05f6740f48c5e96aa260c1a3c84f1f697e3c5fb4da2d9ba46ada39bbd09ca261" %}
{% set intervene = "0.6.4" %}
{% set pybedtools = "0.7.10" %}
{% set pyvcf = "0.6.8" %}
{% set scipy = "1.1.0" %}
{% set tqdm = "4.23.4" %}


package:
  name: {{ name|lower }}
  version: {{ environ.get('VERSION', None) or version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/COMBAT-TB/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ environ.get('SHA', None) or sha256 }}

build:
  script_env:
    - SHA
    - VERSION
    - CONDA_BLD_PATH
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - click
    - intervene {{ intervene }}
    - matplotlib
    - numpy
    - pandas
    - pathlib
    - pybedtools {{ pybedtools }}
    - PyVCF {{ pyvcf }}
    - scipy {{ scipy }}
    - tqdm {{ tqdm }}
    - r-upsetr
    - r-corrplot
    - r-cairo
    - ncurses
    - jinja2
    - libiconv
  run:
    - python
    - click
    - intervene {{ intervene }}
    - matplotlib
    - numpy
    - pandas
    - pathlib
    - pybedtools {{ pybedtools }}
    - PyVCF {{ pyvcf }}
    - scipy {{ scipy }}
    - tqdm {{ tqdm }}
    - r-upsetr
    - r-corrplot
    - r-cairo
    - ncurses
    - jinja2
    - libiconv

test:
  imports:
    - vcf_snps_utils
  commands:
    - vcf_snps_utils --help 2>&1 |grep VCF_DIR >/dev/null

about:
  home: https://github.com/COMBAT-TB/{{ name }}
  license: Apache License 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Custom command line utility tools to manipulate vcf files'
